-- boxscore data: batting/fielding/pitching stats for each player in a game

with

src as (
    select * from {{ source('statsapi', 'game_boxscore') }}
)

select
    partition_0 as season,
    game_pk,
    team_id,
    person_id as player_id,
    gamestatus_isonbench as is_on_bench,
    gamestatus_issubstitute as is_substitute,
    position_abbreviation,
    position_name,
    position_type,
    stats_batting_atbats as batting_atbats,
    {{ string_to_double_check('stats_batting_atbatsperhomerun') }} as batting_atbatsperhomerun,
    stats_batting_baseonballs as batting_baseonballs,
    stats_batting_catchersinterference as batting_catchersinterference,
    stats_batting_caughtstealing as batting_caughtstealing,
    stats_batting_doubles as batting_doubles,
    stats_batting_flyouts as batting_flyouts,
    stats_batting_gamesplayed as batting_gamesplayed,
    stats_batting_groundintodoubleplay as batting_groundintodoubleplay,
    stats_batting_groundintotripleplay as batting_groundintotripleplay,
    stats_batting_groundouts as batting_groundouts,
    stats_batting_hitbypitch as batting_hitbypitch,
    stats_batting_hits as batting_hits,
    stats_batting_homeruns as batting_homeruns,
    stats_batting_intentionalwalks as batting_intentionalwalks,
    stats_batting_leftonbase as batting_leftonbase,
    stats_batting_pickoffs as batting_pickoffs,
    stats_batting_plateappearances as batting_plateappearances,
    stats_batting_rbi as batting_rbi,
    stats_batting_runs as batting_runs,
    stats_batting_sacbunts as batting_sacbunts,
    stats_batting_sacflies as batting_sacflies,
    {{ string_to_double_check('stats_batting_stolenbasepercentage') }} as batting_stolenbasepercentage,
    stats_batting_stolenbases as batting_stolenbases,
    stats_batting_strikeouts as batting_strikeouts,
    stats_batting_totalbases as batting_totalbases,
    stats_batting_triples as batting_triples,
    stats_fielding_assists as fielding_assists,
    stats_fielding_caughtstealing as fielding_caughtstealing,
    stats_fielding_chances as fielding_chances,
    stats_fielding_errors as fielding_errors,
    stats_fielding_gamesstarted as fielding_gamesstarted,
    stats_fielding_passedball as fielding_passedball,
    stats_fielding_pickoffs as fielding_pickoffs,
    stats_fielding_putouts as fielding_putouts,
    {{ string_to_double_check('stats_fielding_stolenbasepercentage') }} as fielding_stolenbasepercentage,
    stats_fielding_stolenbases as fielding_stolenbases,
    stats_pitching_airouts as pitching_airouts,
    stats_pitching_atbats as pitching_atbats,
    stats_pitching_balks as pitching_balks,
    stats_pitching_balls as pitching_balls,
    stats_pitching_baseonballs as pitching_baseonballs,
    stats_pitching_battersfaced as pitching_battersfaced,
    stats_pitching_blownsaves as pitching_blownsaves,
    stats_pitching_catchersinterference as pitching_catchersinterference,
    stats_pitching_caughtstealing as pitching_caughtstealing,
    stats_pitching_completegames as pitching_completegames,
    stats_pitching_doubles as pitching_doubles,
    stats_pitching_earnedruns as pitching_earnedruns,
    stats_pitching_flyouts as pitching_flyouts,
    stats_pitching_gamesfinished as pitching_gamesfinished,
    stats_pitching_gamespitched as pitching_gamespitched,
    stats_pitching_gamesplayed as pitching_gamesplayed,
    stats_pitching_gamesstarted as pitching_gamesstarted,
    stats_pitching_groundouts as pitching_groundouts,
    stats_pitching_hitbatsmen as pitching_hitbatsmen,
    stats_pitching_hitbypitch as pitching_hitbypitch,
    stats_pitching_hits as pitching_hits,
    stats_pitching_holds as pitching_holds,
    stats_pitching_homeruns as pitching_homeruns,
    {{ string_to_double_check('stats_pitching_homerunsper9') }} as pitching_homerunsper9,
    stats_pitching_inheritedrunners as pitching_inheritedrunners,
    stats_pitching_inheritedrunnersscored as pitching_inheritedrunnersscored,
    stats_pitching_inningspitched as pitching_inningspitched,
    stats_pitching_intentionalwalks as pitching_intentionalwalks,
    stats_pitching_losses as pitching_losses,
    stats_pitching_numberofpitches as pitching_numberofpitches,
    stats_pitching_outs as pitching_outs,
    stats_pitching_passedball as pitching_passedball,
    stats_pitching_pickoffs as pitching_pickoffs,
    stats_pitching_pitchesthrown as pitching_pitchesthrown,
    stats_pitching_rbi as pitching_rbi,
    stats_pitching_runs as pitching_runs,
    {{ string_to_double_check('stats_pitching_runsscoredper9') }} as pitching_runsscoredper9,
    stats_pitching_sacbunts as pitching_sacbunts,
    stats_pitching_sacflies as pitching_sacflies,
    stats_pitching_saveopportunities as pitching_saveopportunities,
    stats_pitching_saves as pitching_saves,
    stats_pitching_shutouts as pitching_shutouts,
    {{ string_to_double_check('stats_pitching_stolenbasepercentage') }} as pitching_stolenbasepercentage,
    stats_pitching_stolenbases as pitching_stolenbases,
    stats_pitching_strikeouts as pitching_strikeouts,
    {{ string_to_double_check('stats_pitching_strikepercentage') }} as pitching_strikepercentage,
    stats_pitching_strikes as pitching_strikes,
    stats_pitching_triples as pitching_triples,
    stats_pitching_wildpitches as pitching_wildpitches,
    stats_pitching_wins as pitching_wins

from src
