version: 2

models:
  - name: stg_player_info
    description: "Player info extracted from their last played game"
    columns:
      - name: player_id
        tests:
          - unique
          - not_null
      - name: batside_code
      - name: batside_description
      - name: birthcity
      - name: birthcountry
      - name: birthdate
      - name: birthstateprovince
      - name: boxscorename
      - name: currentage
      - name: firstlastname
      - name: firstname
      - name: fullfmlname
      - name: fulllfmname
      - name: fullname
      - name: height
      - name: initlastname
      - name: lastfirstname
      - name: lastinitname
      - name: lastname
      - name: lastplayeddate
      - name: middlename
      - name: mlbdebutdate
      - name: namefirstlast
      - name: namematrilineal
      - name: pitchhand_code
      - name: pitchhand_description
      - name: primaryposition_abbreviation
      - name: primaryposition_code
      - name: primaryposition_name
      - name: primaryposition_type
      - name: strikezonebottom
      - name: strikezonetop
      - name: uselastname
      - name: usename
      - name: weight
      - name: partition_0